# Generated by Django 3.2.3 on 2021-06-10 08:58

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Product category name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.CharField(max_length=1000, verbose_name='Product Detail'),
        ),
        migrations.AlterField(
            model_name='products',
            name='looks',
            field=models.ImageField(upload_to=services.models.vendor_directory_path, verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Rating',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=2, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='services',
            name='closing_time',
            field=models.TimeField(null=True, verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='services',
            name='cover',
            field=models.ImageField(upload_to=services.models.vendor_directory_path, verbose_name='Vendor image cover'),
        ),
        migrations.AlterField(
            model_name='services',
            name='location',
            field=models.CharField(max_length=200, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='opening_time',
            field=models.TimeField(null=True, verbose_name='Opening Time'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.CharField(choices=[('REST', 'restaurant'), ('PARTY', 'party'), ('PHAR', 'pharmacy'), ('GRO', 'groceries'), ('CLOTH', 'clothing')], max_length=6, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Tag Name'),
        ),
    ]
