# Generated by Django 3.2.3 on 2021-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210610_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Rating',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=2, null=True, verbose_name='Rating'),
        ),
    ]
