# Generated by Django 3.2.3 on 2021-06-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Vendor',
        ),
    ]
