# Generated by Django 3.2.3 on 2021-06-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_schedule_closed_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='service',
            field=models.CharField(choices=[('REST', 'Restaurant'), ('PARTY', 'Party'), ('PHAR', 'Pharmacy'), ('GRO', 'Groceries'), ('CLOTH', 'Clothing')], max_length=6, verbose_name='Service'),
        ),
    ]
