# Generated by Django 3.2.3 on 2021-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_schedule_closed_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug_name',
            field=models.SlugField(db_index=False, null=True),
        ),
    ]
