# Generated by Django 3.2.3 on 2021-06-16 09:07

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_productcategory_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.CharField(max_length=1000, null=True, verbose_name='Product Detail'),
        ),
        migrations.AlterField(
            model_name='products',
            name='looks',
            field=models.ImageField(null=True, upload_to=services.models.product_directory_path, verbose_name='Product Image'),
        ),
    ]
