# Generated by Django 3.2.3 on 2021-06-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_name',
            field=models.SlugField(db_index=False, null=True),
        ),
    ]
