# Generated by Django 3.2.3 on 2021-06-17 11:28

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_product_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=models.SET(services.models.products_category_set), to='services.productcategory'),
        ),
    ]
