# Generated by Django 3.2.3 on 2021-06-18 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_customercart_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.vendor'),
            preserve_default=False,
        ),
    ]
