# Generated by Django 3.2.3 on 2021-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_customercart_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivered_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='ordered_time',
            field=models.TimeField(null=True),
        ),
    ]
