# Generated by Django 3.2.3 on 2021-06-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20210618_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customercart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='customercart',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='delivered_time',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='ordered_time',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='products',
        ),
        migrations.AddField(
            model_name='customercart',
            name='delivered_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='customercart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customercart',
            name='ordered_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='customercart',
            name='products',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.customercart'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.product'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.vendor'),
        ),
    ]
