# Generated by Django 3.2.3 on 2021-06-22 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0018_auto_20210620_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercart',
            old_name='final_price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='customercart',
            name='products',
        ),
        migrations.AddField(
            model_name='customercart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.product'),
        ),
        migrations.AddField(
            model_name='customercart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customercart',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.vendor'),
        ),
        migrations.AlterField(
            model_name='customercart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
