# Generated by Django 3.2.3 on 2021-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_checkout_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='transit_distance',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='transit_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='address'),
        ),
    ]
