# Generated by Django 3.2.3 on 2021-06-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_userlocation_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='transit_distance',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
