# Generated by Django 3.2.3 on 2021-06-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20210625_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='transit_distance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
